### ISSUE TITLE
Incorrect Server Status

### ISSUE THREAD

**Issue by laksith19** [compserv/hivemind#7]
The website seems to report a lot of the machines are unavailable when it's still possible to connect to some of them. I've tired this with `cory`, `hive1`, and `hive2`.

**Comment by steven676** [comment]
The affected machines were recently upgraded to Ubuntu 22.04, which no longer accepts the legacy `ssh-rsa` signature algorithm for user SSH keys because it relies on the [weak SHA-1 hash algorithm](https://www.openssh.com/txt/release-8.8).  You can either upgrade your SSH client to a version, such as OpenSSH 7.2 or later, that supports `rsa-sha2-256` or `rsa-sha2-512` signatures (which use the same RSA keys as `ssh-rsa` does), or switch to an ECDSA or Ed25519 key to be able to SSH into these machines.

**Comment by oliver-ni** [comment]
Thanks for the report. We've update the SSH client and will also switch to an ecdsa key just to be up to date.

The site is now fully functional again.
